### ISSUE TITLE
can the deepnote run on localhost？

### ISSUE THREAD

**Issue by wspspring** [ramene/awesome-deepnote#1]
can the deepnote run on localhost？

**Comment by SuNaden** [comment]
Hey @wspspring sadly not yet - we are still working on local execution. Right now all notebooks are ran in the cloud.

**Comment by ramene** [comment]
@wspspring I'd highly recommend joining the Deepnote community where you can track this same [discussion](https://community.deepnote.com/c/suggestions/implement-local-execution)

HTH
